SET local check_function_bodies = off;

CREATE TABLE "public"."app_settings" (
  "key"        text                     NOT NULL,
  "value"      text                     NOT NULL,
  "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "app_settings_pkey" PRIMARY KEY (key)
);

ALTER TABLE "public"."app_settings"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."expense_activity" (
  "id"               bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "expense_id"       bigint,
  "expense_category" text,
  "user_id"          uuid,
  "user_name"        text,
  "action"           text                     NOT NULL,
  "field_name"       text,
  "old_value"        text,
  "new_value"        text,
  "created_at"       timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "expense_activity_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."expense_activity"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."expenses" (
  "id"           bigint                   GENERATED ALWAYS AS IDENTITY NOT NULL,
  "expense_date" date                     NOT NULL,
  "category"     text                     NOT NULL,
  "amount"       numeric                  NOT NULL,
  "note"         text,
  "user_id"      uuid,
  "user_name"    text,
  "created_at"   timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "expenses_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."expenses"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."gst_rate_history" (
  "id"             bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "rate"           numeric(5,2)             NOT NULL,
  "effective_from" date                     NOT NULL,
  "created_by"     uuid,
  "created_at"     timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "gst_rate_history_pkey" PRIMARY KEY (id),
  CONSTRAINT "gst_rate_history_rate_check" CHECK ((rate >= (0)::numeric))
);

ALTER TABLE "public"."gst_rate_history"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."order_activity" (
  "id"         bigint                   GENERATED ALWAYS AS IDENTITY NOT NULL,
  "order_id"   bigint                   NOT NULL,
  "user_id"    uuid,
  "user_name"  text,
  "action"     text                     NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "field_name" text,
  "old_value"  text,
  "new_value"  text,
  CONSTRAINT "order_activity_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."order_activity"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."order_item_history" (
  "id"           bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_id"     bigint                   NOT NULL,
  "product_id"   bigint,
  "product_name" text,
  "unit_price"   numeric(10,2),
  "quantity"     integer,
  "action"       text,
  "timestamp"    timestamp with time zone DEFAULT now(),
  "created_at"   timestamp with time zone DEFAULT now(),
  CONSTRAINT "order_item_history_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."order_item_history"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."order_items" (
  "id"           bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_id"     bigint                   NOT NULL,
  "product_id"   bigint,
  "product_name" text                     NOT NULL,
  "unit_price"   numeric(10,2)            NOT NULL DEFAULT 0,
  "unit_cost"    numeric(10,2)            NOT NULL DEFAULT 0,
  "quantity"     integer                  NOT NULL DEFAULT 1,
  "line_total"   numeric(10,2)            NOT NULL DEFAULT 0,
  "created_at"   timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "order_items_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."order_items"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."orders" (
  "id"                  bigint                   GENERATED ALWAYS AS IDENTITY NOT NULL,
  "num"                 integer,
  "customer_name"       text,
  "contact"             text,
  "product"             text,
  "price"               numeric,
  "delivery"            text,
  "payment"             text,
  "notes"               text,
  "status"              text                     DEFAULT 'pending'::text,
  "order_date"          date                     DEFAULT CURRENT_DATE,
  "order_time"          text,
  "created_at"          timestamp with time zone DEFAULT now(),
  "payment_done"        boolean                  DEFAULT false,
  "variant_id"          bigint,
  "stock_deducted"      boolean                  NOT NULL DEFAULT false,
  "product_id"          bigint,
  "total_cost"          numeric(10,2)            DEFAULT 0,
  "discount_amount"     numeric(10,2)            DEFAULT 0,
  "discount_reason"     text,
  "weighted_avg_price"  numeric(10,2)            DEFAULT 0,
  "total_qty"           integer                  DEFAULT 0,
  "pending_item_return" boolean                  DEFAULT false,
  "item_returned_at"    timestamp with time zone,
  CONSTRAINT "orders_date_num_unique" UNIQUE (order_date, num),
  CONSTRAINT "orders_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."orders"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."product_activity" (
  "id"           bigint                   GENERATED ALWAYS AS IDENTITY NOT NULL,
  "product_id"   bigint                   NOT NULL,
  "product_name" text,
  "user_id"      uuid,
  "user_name"    text,
  "action"       text                     NOT NULL,
  "field_name"   text,
  "old_value"    text,
  "new_value"    text,
  "created_at"   timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "product_activity_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."product_activity"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."products" (
  "id"                  bigint                   GENERATED ALWAYS AS IDENTITY NOT NULL,
  "name"                text                     NOT NULL,
  "price"               numeric                  DEFAULT 0,
  "active"              boolean                  DEFAULT true,
  "created_at"          timestamp with time zone DEFAULT now(),
  "image_url"           text,
  "cost_price"          numeric(10,2)            DEFAULT 0,
  "selling_price"       numeric(10,2)            DEFAULT 0,
  "color"               text,
  "stock_qty"           integer                  NOT NULL DEFAULT 0,
  "low_stock_threshold" integer                  NOT NULL DEFAULT 3,
  "promo_price"         numeric(10,2),
  "promo_start"         date,
  "promo_end"           date,
  CONSTRAINT "products_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."products"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."profiles" (
  "id"         uuid                     NOT NULL,
  "full_name"  text,
  "role"       text                     NOT NULL DEFAULT 'order_collection'::text,
  "is_active"  boolean                  DEFAULT true,
  "created_at" timestamp with time zone DEFAULT now(),
  "avatar_url" text,
  CONSTRAINT "profiles_pkey" PRIMARY KEY (id),
  CONSTRAINT "profiles_role_check" CHECK ((role = ANY (ARRAY['admin'::text, 'manager'::text, 'delivery'::text])))
);

ALTER TABLE "public"."profiles"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."push_subscriptions" (
  "id"         bigint                   GENERATED ALWAYS AS IDENTITY NOT NULL,
  "user_id"    uuid                     NOT NULL,
  "role"       text                     NOT NULL,
  "endpoint"   text                     NOT NULL,
  "p256dh"     text                     NOT NULL,
  "auth"       text                     NOT NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  CONSTRAINT "push_subscriptions_endpoint_key" UNIQUE (endpoint),
  CONSTRAINT "push_subscriptions_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."push_subscriptions"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."stock_entries" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "product_id" bigint                   NOT NULL,
  "quantity"   integer                  NOT NULL,
  "cost_price" numeric(10,2)            NOT NULL,
  "reason"     text,
  "active"     boolean                  DEFAULT true,
  "created_at" timestamp with time zone DEFAULT now(),
  "added_by"   text,
  "notes"      text,
  CONSTRAINT "stock_entries_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."stock_entries"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."stock_movements" (
  "id"         bigint                   GENERATED ALWAYS AS IDENTITY NOT NULL,
  "variant_id" bigint,
  "order_id"   bigint,
  "change_qty" integer                  NOT NULL,
  "reason"     text                     NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "cost_price" numeric(10,2),
  "product_id" bigint,
  CONSTRAINT "stock_movements_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."stock_movements"
  ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.adjust_stock (
  p_product_id bigint,
  p_change     integer
)
  RETURNS void
  LANGUAGE sql
  SECURITY DEFINER
  AS $function$ UPDATE products SET stock_qty = GREATEST(0, COALESCE(stock_qty,0) + p_change) WHERE id = p_product_id; $function$;

CREATE OR REPLACE FUNCTION public.get_my_role()
  RETURNS text
  LANGUAGE sql
  STABLE
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
  select role from public.profiles where id = auth.uid();
$function$;

CREATE OR REPLACE FUNCTION public.handle_new_user()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SECURITY DEFINER
  AS $function$
BEGIN
  INSERT INTO public.profiles (id, full_name, role, is_active)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)),
    COALESCE(new.raw_user_meta_data->>'role', 'order_collection'),
    true
  )
  ON CONFLICT (id) DO UPDATE SET
    full_name = EXCLUDED.full_name,
    role = EXCLUDED.role;
  RETURN new;
END;
$function$;

CREATE OR REPLACE FUNCTION public.process_stock_change (
  p_product_id bigint,
  p_order_id   bigint,
  p_change     integer,
  p_reason     text
)
  RETURNS void
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
begin
  update public.products
  set stock_qty = greatest(0, coalesce(stock_qty, 0) + p_change)
  where id = p_product_id;

  update public.orders
  set stock_deducted = (p_change < 0)
  where id = p_order_id;

  insert into public.stock_movements (product_id, order_id, change_qty, reason)
  values (p_product_id, p_order_id, p_change, p_reason);
end;
$function$;

ALTER TABLE "public"."gst_rate_history"
  ADD CONSTRAINT "gst_rate_history_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id);

ALTER TABLE "public"."order_activity"
  ADD CONSTRAINT "fk_order_activity_order" FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE;

ALTER TABLE "public"."order_item_history"
  ADD CONSTRAINT "order_item_history_order_id_fkey" FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE;

ALTER TABLE "public"."order_items"
  ADD CONSTRAINT "order_items_order_id_fkey" FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE;

ALTER TABLE "public"."order_items"
  ADD CONSTRAINT "order_items_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(id);

ALTER TABLE "public"."orders"
  ADD CONSTRAINT "orders_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(id);

ALTER TABLE "public"."product_activity"
  ADD CONSTRAINT "fk_product_activity_product" FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;

ALTER TABLE "public"."profiles"
  ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."push_subscriptions"
  ADD CONSTRAINT "push_subscriptions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."stock_entries"
  ADD CONSTRAINT "stock_entries_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;

ALTER TABLE "public"."stock_movements"
  ADD CONSTRAINT "stock_movements_order_id_fkey" FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE SET NULL;

ALTER TABLE "public"."stock_movements"
  ADD CONSTRAINT "stock_movements_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(id);

CREATE INDEX expense_activity_expense_id_idx ON public.expense_activity USING btree (expense_id);

CREATE INDEX idx_order_activity_order_id ON public.order_activity USING btree (order_id);

CREATE INDEX idx_orders_date_status ON public.orders USING btree (order_date, status);

CREATE INDEX idx_product_activity_product_id ON public.product_activity USING btree (product_id);

CREATE INDEX idx_stock_entries_active ON public.stock_entries USING btree (product_id, active);

CREATE INDEX idx_stock_entries_created ON public.stock_entries USING btree (created_at DESC);

CREATE INDEX idx_stock_entries_product ON public.stock_entries USING btree (product_id);

CREATE INDEX order_items_order_id_idx ON public.order_items USING btree (order_id);

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

CREATE POLICY "app_settings_select_authenticated" ON "public"."app_settings"
  FOR SELECT
  TO "authenticated"
  USING (true);

CREATE POLICY "app_settings_select" ON "public"."app_settings"
  FOR SELECT
  TO PUBLIC
  USING ((public.get_my_role() = ANY (ARRAY['admin'::text, 'manager'::text])));

CREATE POLICY "app_settings_update" ON "public"."app_settings"
  FOR UPDATE
  TO PUBLIC
  USING ((public.get_my_role() = 'admin'::text));

CREATE POLICY "app_settings_write_admin_only" ON "public"."app_settings"
  FOR ALL
  TO "authenticated"
  USING ((public.get_my_role() = 'admin'::text))
  WITH CHECK ((public.get_my_role() = 'admin'::text));

CREATE POLICY "expense_activity_insert" ON "public"."expense_activity"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((public.get_my_role() IS NOT NULL));

CREATE POLICY "expense_activity_select" ON "public"."expense_activity"
  FOR SELECT
  TO PUBLIC
  USING ((public.get_my_role() = ANY (ARRAY['admin'::text, 'manager'::text])));

CREATE POLICY "expenses_delete" ON "public"."expenses"
  FOR DELETE
  TO PUBLIC
  USING ((public.get_my_role() = 'admin'::text));

CREATE POLICY "expenses_insert" ON "public"."expenses"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((public.get_my_role() = ANY (ARRAY['admin'::text, 'manager'::text])));

CREATE POLICY "expenses_select" ON "public"."expenses"
  FOR SELECT
  TO PUBLIC
  USING ((public.get_my_role() = ANY (ARRAY['admin'::text, 'manager'::text])));

CREATE POLICY "expenses_update" ON "public"."expenses"
  FOR UPDATE
  TO PUBLIC
  USING ((public.get_my_role() = ANY (ARRAY['admin'::text, 'manager'::text])));

CREATE POLICY "gst_rates_insert_admin_only" ON "public"."gst_rate_history"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((public.get_my_role() = 'admin'::text));

CREATE POLICY "gst_rates_select_admin_manager" ON "public"."gst_rate_history"
  FOR SELECT
  TO "authenticated"
  USING ((public.get_my_role() = ANY (ARRAY['admin'::text, 'manager'::text])));

CREATE POLICY "order_activity_insert" ON "public"."order_activity"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((public.get_my_role() IS NOT NULL));

CREATE POLICY "order_activity_select" ON "public"."order_activity"
  FOR SELECT
  TO PUBLIC
  USING ((public.get_my_role() IS NOT NULL));

CREATE POLICY "Log item changes" ON "public"."order_item_history"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((public.get_my_role() = ANY (ARRAY['admin'::text, 'manager'::text])));

CREATE POLICY "View item history" ON "public"."order_item_history"
  FOR SELECT
  TO PUBLIC
  USING ((EXISTS ( SELECT 1
   FROM public.orders o
  WHERE
    ((o.id = order_item_history.order_id) AND ((public.get_my_role() = 'admin'::text) OR (public.get_my_role() = 'manager'::text) OR ((public.get_my_role() = 'delivery'::text) AND
    (o.delivery = auth.email())))))));

CREATE POLICY "order_items_delete" ON "public"."order_items"
  FOR DELETE
  TO PUBLIC
  USING ((public.get_my_role() = ANY (ARRAY['admin'::text, 'manager'::text])));

CREATE POLICY "order_items_insert" ON "public"."order_items"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((public.get_my_role() = ANY (ARRAY['admin'::text, 'manager'::text])));

CREATE POLICY "order_items_select" ON "public"."order_items"
  FOR SELECT
  TO PUBLIC
  USING ((public.get_my_role() IS NOT NULL));

CREATE POLICY "orders_delete" ON "public"."orders"
  FOR DELETE
  TO PUBLIC
  USING ((public.get_my_role() = 'admin'::text));

CREATE POLICY "orders_insert" ON "public"."orders"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((public.get_my_role() = ANY (ARRAY['admin'::text, 'manager'::text])));

CREATE POLICY "orders_select" ON "public"."orders"
  FOR SELECT
  TO PUBLIC
  USING ((public.get_my_role() IS NOT NULL));

CREATE POLICY "orders_update_admin" ON "public"."orders"
  FOR UPDATE
  TO PUBLIC
  USING ((public.get_my_role() = 'admin'::text));

CREATE POLICY "orders_update_delivery" ON "public"."orders"
  FOR UPDATE
  TO PUBLIC
  USING (((public.get_my_role() = 'delivery'::text) AND (status = 'packed'::text)))
  WITH CHECK ((status = 'delivered'::text));

CREATE POLICY "orders_update_manager" ON "public"."orders"
  FOR UPDATE
  TO PUBLIC
  USING ((public.get_my_role() = 'manager'::text));

CREATE POLICY "product_activity_insert" ON "public"."product_activity"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((public.get_my_role() IS NOT NULL));

CREATE POLICY "product_activity_select" ON "public"."product_activity"
  FOR SELECT
  TO PUBLIC
  USING ((public.get_my_role() = 'admin'::text));

CREATE POLICY "products_delete" ON "public"."products"
  FOR DELETE
  TO PUBLIC
  USING ((public.get_my_role() = 'admin'::text));

CREATE POLICY "products_insert" ON "public"."products"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((public.get_my_role() = 'admin'::text));

CREATE POLICY "products_select" ON "public"."products"
  FOR SELECT
  TO PUBLIC
  USING ((public.get_my_role() IS NOT NULL));

CREATE POLICY "products_update" ON "public"."products"
  FOR UPDATE
  TO PUBLIC
  USING ((public.get_my_role() = 'admin'::text));

CREATE POLICY "profiles_insert_admin_only" ON "public"."profiles"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((public.get_my_role() = 'admin'::text));

CREATE POLICY "profiles_insert" ON "public"."profiles"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (((public.get_my_role() = 'admin'::text) OR (id = auth.uid())));

CREATE POLICY "profiles_select_own_or_admin" ON "public"."profiles"
  FOR SELECT
  TO "authenticated"
  USING (((id = auth.uid()) OR (public.get_my_role() = 'admin'::text)));

CREATE POLICY "profiles_select" ON "public"."profiles"
  FOR SELECT
  TO PUBLIC
  USING (((id = auth.uid()) OR (public.get_my_role() = 'admin'::text)));

CREATE POLICY "profiles_update_admin_only" ON "public"."profiles"
  FOR UPDATE
  TO "authenticated"
  USING ((public.get_my_role() = 'admin'::text))
  WITH CHECK ((public.get_my_role() = 'admin'::text));

CREATE POLICY "profiles_update_own" ON "public"."profiles"
  FOR UPDATE
  TO PUBLIC
  USING ((auth.uid() = id))
  WITH CHECK ((auth.uid() = id));

CREATE POLICY "profiles_update" ON "public"."profiles"
  FOR UPDATE
  TO PUBLIC
  USING ((public.get_my_role() = 'admin'::text));

CREATE POLICY "push_subscriptions_delete_own" ON "public"."push_subscriptions"
  FOR DELETE
  TO PUBLIC
  USING ((auth.uid() = user_id));

CREATE POLICY "push_subscriptions_insert_own" ON "public"."push_subscriptions"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "push_subscriptions_select_own" ON "public"."push_subscriptions"
  FOR SELECT
  TO PUBLIC
  USING ((auth.uid() = user_id));

CREATE POLICY "Deactivate entries" ON "public"."stock_entries"
  FOR UPDATE
  TO PUBLIC
  USING ((public.get_my_role() = ANY (ARRAY['admin'::text, 'manager'::text])))
  WITH CHECK ((public.get_my_role() = ANY (ARRAY['admin'::text, 'manager'::text])));

CREATE POLICY "Log stock entries" ON "public"."stock_entries"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((public.get_my_role() = ANY (ARRAY['admin'::text, 'manager'::text])));

CREATE POLICY "View stock entries" ON "public"."stock_entries"
  FOR SELECT
  TO PUBLIC
  USING ((EXISTS ( SELECT 1
   FROM public.products p
  WHERE ((p.id = stock_entries.product_id) AND ((public.get_my_role() = 'admin'::text) OR (public.get_my_role() = 'manager'::text))))));

CREATE POLICY "stock_movements_insert" ON "public"."stock_movements"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((public.get_my_role() IS NOT NULL));

CREATE POLICY "stock_movements_select" ON "public"."stock_movements"
  FOR SELECT
  TO PUBLIC
  USING ((public.get_my_role() = 'admin'::text));

CREATE POLICY "Authenticated delete" ON "storage"."objects"
  FOR DELETE
  TO "authenticated"
  USING ((bucket_id = 'product-images'::text));

CREATE POLICY "Authenticated upload" ON "storage"."objects"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((bucket_id = 'product-images'::text));

CREATE POLICY "Public read access" ON "storage"."objects"
  FOR SELECT
  TO PUBLIC
  USING ((bucket_id = 'product-images'::text));

CREATE POLICY "avatars_delete_own" ON "storage"."objects"
  FOR DELETE
  TO PUBLIC
  USING (((bucket_id = 'avatars'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));

CREATE POLICY "avatars_insert_own" ON "storage"."objects"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (((bucket_id = 'avatars'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));

CREATE POLICY "avatars_public_read" ON "storage"."objects"
  FOR SELECT
  TO PUBLIC
  USING ((bucket_id = 'avatars'::text));

CREATE POLICY "avatars_update_own" ON "storage"."objects"
  FOR UPDATE
  TO PUBLIC
  USING (((bucket_id = 'avatars'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));

GRANT EXECUTE ON FUNCTION "public"."adjust_stock"(bigint, integer) TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."get_my_role"() TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."handle_new_user"() TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."process_stock_change"(bigint, bigint, integer, text) TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."app_settings" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."expense_activity" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."expenses" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."gst_rate_history" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."order_activity" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."order_item_history" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."order_items" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."orders" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."product_activity" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."products" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."profiles" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."push_subscriptions" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."stock_entries" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."stock_movements" TO "anon", "authenticated", "postgres", "service_role";

